image: python:latest

stages:
- linting
- test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose .

test:
  stage: test
  script:
    - pip3 install -r requirements/prod.txt
    - pip3 install -r requirements/test.txt
    - cd lyceum
    - python3 manage.py test